### PR TITLE
Kafka river

### PR DESCRIPTION
**Pull request by mfrdrcks**
This updates the values.yaml file to allow for remote access to Kafka, with a modified README.md to document what is needed to set up the remote access.

### CODE REVIEW

**Comment by BenGalewsky** [comment]
Deployment needs to include the namespace in the advertised host, otherwise we can't reach this from a different namespace.

Also, when deploying this on River, please use Helm's -n option to give the app a better name than "release-name".

Ideally we would also deploy Kafka to its own namespace and not clutter the `ServiceX`namespace

**Comment by robrwg** [comment]
> Ideally we would also deploy Kafka to its own namespace and not clutter the ServiceX namespace

We may need a discussion on deployment management on the SSL (currently just River, hopefully others will join).   For example, https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ has some interesting principles.

**Comment by mfrdrcks** [comment]
On River this has been deployed to the Kafka namespace, without external access, with a kafka prefix, and the kafka-manager included. This does not include any SSL authentication, that has been moved to ServiceX issue #72, which will need to be done, but shouldn't hold this up.

The deployment uses the instructions in the README for when Tiller is not available.

**Comment by BenGalewsky** [comment]
This PR has been superseded by [ServiceX Issue 103](https://github.com/ssl-hep/ServiceX/pull/103)

**Pull request closed without merging**
